import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import ProfileCard from "@/components/ProfileCard";
import PostInput from "@/components/PostInput";
import Post from "@/components/Post";
import { useEffect, useState } from "react";
import { Post as PostResponse } from "@/utils/apis";
import { parseJwt } from "@/utils/parse-jwt";
import Cookies from "js-cookie";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  let [posts, setPosts] = useState<PostResponse[]>([]);
  let [username, setUsername] = useState("");
  useEffect(() => {
    refetch()
    if (Cookies.get("token")) {
      const json = parseJwt(Cookies.get("token") || "");
      setUsername(json.username);
    }
  }, []);

  async function refetch() {
    await fetch("/api/posts", {
      method: "GET",
      headers: { "Content-Type": "application/json" },
      credentials: "same-origin",
    })
      .then((response) => response.json())
      .then((data) => setPosts(data));
  }

  return (
    <>
      <Navbar />
      <Head>
        <title>My Social</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            padding: "20px",
            width: "70%",
            minWidth: "0",
          }}
        >
          <ProfileCard
            profileImage="/profile.png"
            name={username}
            title="Ex-KBTG | Full-Stack Developer"
            viewers={7}
            // connections={67}
          />
          <div
            style={{
              display: "flex",
              justifyContent: "flex-start",
              flexDirection: "column",
              width: "80%",
              minWidth: "0",
            }}
          >
            <PostInput refetch={refetch}/>
            <hr
              style={{
                width: "100%",
                maxWidth: "700px",
                textAlign: "left",
                marginLeft: "0",
                marginBottom: "25px",
              }}
            ></hr>
            {posts?.map((post) => {
              return (
                <Post
                  key={post.id}
                  id={post.id || ""}
                  author={post.author || ""}
                  content={post.content}
                  refetch={refetch}
                />
              );
            })}  
          </div>
        </div>
        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>
    </>
  );
}
